/*
 * MIT License
 *
 * Copyright (c) 2023 OrdinaryRoad
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TextPiece.proto

package tech.ordinaryroad.live.chat.client.douyin.protobuf.dto;

public final class TextPieceOuterClass {
  private TextPieceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TextPieceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TextPiece)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool type = 1;</code>
     * @return The type.
     */
    boolean getType();

    /**
     * <code>.TextFormat format = 2;</code>
     * @return Whether the format field is set.
     */
    boolean hasFormat();
    /**
     * <code>.TextFormat format = 2;</code>
     * @return The format.
     */
    tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat getFormat();
    /**
     * <code>.TextFormat format = 2;</code>
     */
    tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormatOrBuilder getFormatOrBuilder();

    /**
     * <code>string string_value = 3;</code>
     * @return The stringValue.
     */
    java.lang.String getStringValue();
    /**
     * <code>string string_value = 3;</code>
     * @return The bytes for stringValue.
     */
    com.google.protobuf.ByteString
        getStringValueBytes();

    /**
     * <code>.TextPieceUser user_value = 4;</code>
     * @return Whether the userValue field is set.
     */
    boolean hasUserValue();
    /**
     * <code>.TextPieceUser user_value = 4;</code>
     * @return The userValue.
     */
    tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceUserOuterClass.TextPieceUser getUserValue();
    /**
     * <code>.TextPieceUser user_value = 4;</code>
     */
    tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceUserOuterClass.TextPieceUserOrBuilder getUserValueOrBuilder();

    /**
     * <code>.TextPieceGift gift_value = 5;</code>
     * @return Whether the giftValue field is set.
     */
    boolean hasGiftValue();
    /**
     * <code>.TextPieceGift gift_value = 5;</code>
     * @return The giftValue.
     */
    tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceGiftOuterClass.TextPieceGift getGiftValue();
    /**
     * <code>.TextPieceGift gift_value = 5;</code>
     */
    tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceGiftOuterClass.TextPieceGiftOrBuilder getGiftValueOrBuilder();

    /**
     * <code>.TextPieceHeart heart_value = 6;</code>
     * @return Whether the heartValue field is set.
     */
    boolean hasHeartValue();
    /**
     * <code>.TextPieceHeart heart_value = 6;</code>
     * @return The heartValue.
     */
    tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceHeartOuterClass.TextPieceHeart getHeartValue();
    /**
     * <code>.TextPieceHeart heart_value = 6;</code>
     */
    tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceHeartOuterClass.TextPieceHeartOrBuilder getHeartValueOrBuilder();

    /**
     * <code>.TextPiecePatternRef pattern_ref_value = 7;</code>
     * @return Whether the patternRefValue field is set.
     */
    boolean hasPatternRefValue();
    /**
     * <code>.TextPiecePatternRef pattern_ref_value = 7;</code>
     * @return The patternRefValue.
     */
    tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPiecePatternRefOuterClass.TextPiecePatternRef getPatternRefValue();
    /**
     * <code>.TextPiecePatternRef pattern_ref_value = 7;</code>
     */
    tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPiecePatternRefOuterClass.TextPiecePatternRefOrBuilder getPatternRefValueOrBuilder();

    /**
     * <code>.TextPieceImage image_value = 8;</code>
     * @return Whether the imageValue field is set.
     */
    boolean hasImageValue();
    /**
     * <code>.TextPieceImage image_value = 8;</code>
     * @return The imageValue.
     */
    tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceImageOuterClass.TextPieceImage getImageValue();
    /**
     * <code>.TextPieceImage image_value = 8;</code>
     */
    tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceImageOuterClass.TextPieceImageOrBuilder getImageValueOrBuilder();
  }
  /**
   * Protobuf type {@code TextPiece}
   */
  public static final class TextPiece extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TextPiece)
      TextPieceOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TextPiece.newBuilder() to construct.
    private TextPiece(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TextPiece() {
      stringValue_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TextPiece();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceOuterClass.internal_static_TextPiece_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceOuterClass.internal_static_TextPiece_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceOuterClass.TextPiece.class, tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceOuterClass.TextPiece.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private boolean type_ = false;
    /**
     * <code>bool type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public boolean getType() {
      return type_;
    }

    public static final int FORMAT_FIELD_NUMBER = 2;
    private tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat format_;
    /**
     * <code>.TextFormat format = 2;</code>
     * @return Whether the format field is set.
     */
    @java.lang.Override
    public boolean hasFormat() {
      return format_ != null;
    }
    /**
     * <code>.TextFormat format = 2;</code>
     * @return The format.
     */
    @java.lang.Override
    public tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat getFormat() {
      return format_ == null ? tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat.getDefaultInstance() : format_;
    }
    /**
     * <code>.TextFormat format = 2;</code>
     */
    @java.lang.Override
    public tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormatOrBuilder getFormatOrBuilder() {
      return format_ == null ? tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat.getDefaultInstance() : format_;
    }

    public static final int STRING_VALUE_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object stringValue_ = "";
    /**
     * <code>string string_value = 3;</code>
     * @return The stringValue.
     */
    @java.lang.Override
    public java.lang.String getStringValue() {
      java.lang.Object ref = stringValue_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stringValue_ = s;
        return s;
      }
    }
    /**
     * <code>string string_value = 3;</code>
     * @return The bytes for stringValue.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStringValueBytes() {
      java.lang.Object ref = stringValue_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stringValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_VALUE_FIELD_NUMBER = 4;
    private tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceUserOuterClass.TextPieceUser userValue_;
    /**
     * <code>.TextPieceUser user_value = 4;</code>
     * @return Whether the userValue field is set.
     */
    @java.lang.Override
    public boolean hasUserValue() {
      return userValue_ != null;
    }
    /**
     * <code>.TextPieceUser user_value = 4;</code>
     * @return The userValue.
     */
    @java.lang.Override
    public tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceUserOuterClass.TextPieceUser getUserValue() {
      return userValue_ == null ? tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceUserOuterClass.TextPieceUser.getDefaultInstance() : userValue_;
    }
    /**
     * <code>.TextPieceUser user_value = 4;</code>
     */
    @java.lang.Override
    public tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceUserOuterClass.TextPieceUserOrBuilder getUserValueOrBuilder() {
      return userValue_ == null ? tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceUserOuterClass.TextPieceUser.getDefaultInstance() : userValue_;
    }

    public static final int GIFT_VALUE_FIELD_NUMBER = 5;
    private tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceGiftOuterClass.TextPieceGift giftValue_;
    /**
     * <code>.TextPieceGift gift_value = 5;</code>
     * @return Whether the giftValue field is set.
     */
    @java.lang.Override
    public boolean hasGiftValue() {
      return giftValue_ != null;
    }
    /**
     * <code>.TextPieceGift gift_value = 5;</code>
     * @return The giftValue.
     */
    @java.lang.Override
    public tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceGiftOuterClass.TextPieceGift getGiftValue() {
      return giftValue_ == null ? tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceGiftOuterClass.TextPieceGift.getDefaultInstance() : giftValue_;
    }
    /**
     * <code>.TextPieceGift gift_value = 5;</code>
     */
    @java.lang.Override
    public tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceGiftOuterClass.TextPieceGiftOrBuilder getGiftValueOrBuilder() {
      return giftValue_ == null ? tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceGiftOuterClass.TextPieceGift.getDefaultInstance() : giftValue_;
    }

    public static final int HEART_VALUE_FIELD_NUMBER = 6;
    private tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceHeartOuterClass.TextPieceHeart heartValue_;
    /**
     * <code>.TextPieceHeart heart_value = 6;</code>
     * @return Whether the heartValue field is set.
     */
    @java.lang.Override
    public boolean hasHeartValue() {
      return heartValue_ != null;
    }
    /**
     * <code>.TextPieceHeart heart_value = 6;</code>
     * @return The heartValue.
     */
    @java.lang.Override
    public tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceHeartOuterClass.TextPieceHeart getHeartValue() {
      return heartValue_ == null ? tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceHeartOuterClass.TextPieceHeart.getDefaultInstance() : heartValue_;
    }
    /**
     * <code>.TextPieceHeart heart_value = 6;</code>
     */
    @java.lang.Override
    public tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceHeartOuterClass.TextPieceHeartOrBuilder getHeartValueOrBuilder() {
      return heartValue_ == null ? tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceHeartOuterClass.TextPieceHeart.getDefaultInstance() : heartValue_;
    }

    public static final int PATTERN_REF_VALUE_FIELD_NUMBER = 7;
    private tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPiecePatternRefOuterClass.TextPiecePatternRef patternRefValue_;
    /**
     * <code>.TextPiecePatternRef pattern_ref_value = 7;</code>
     * @return Whether the patternRefValue field is set.
     */
    @java.lang.Override
    public boolean hasPatternRefValue() {
      return patternRefValue_ != null;
    }
    /**
     * <code>.TextPiecePatternRef pattern_ref_value = 7;</code>
     * @return The patternRefValue.
     */
    @java.lang.Override
    public tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPiecePatternRefOuterClass.TextPiecePatternRef getPatternRefValue() {
      return patternRefValue_ == null ? tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPiecePatternRefOuterClass.TextPiecePatternRef.getDefaultInstance() : patternRefValue_;
    }
    /**
     * <code>.TextPiecePatternRef pattern_ref_value = 7;</code>
     */
    @java.lang.Override
    public tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPiecePatternRefOuterClass.TextPiecePatternRefOrBuilder getPatternRefValueOrBuilder() {
      return patternRefValue_ == null ? tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPiecePatternRefOuterClass.TextPiecePatternRef.getDefaultInstance() : patternRefValue_;
    }

    public static final int IMAGE_VALUE_FIELD_NUMBER = 8;
    private tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceImageOuterClass.TextPieceImage imageValue_;
    /**
     * <code>.TextPieceImage image_value = 8;</code>
     * @return Whether the imageValue field is set.
     */
    @java.lang.Override
    public boolean hasImageValue() {
      return imageValue_ != null;
    }
    /**
     * <code>.TextPieceImage image_value = 8;</code>
     * @return The imageValue.
     */
    @java.lang.Override
    public tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceImageOuterClass.TextPieceImage getImageValue() {
      return imageValue_ == null ? tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceImageOuterClass.TextPieceImage.getDefaultInstance() : imageValue_;
    }
    /**
     * <code>.TextPieceImage image_value = 8;</code>
     */
    @java.lang.Override
    public tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceImageOuterClass.TextPieceImageOrBuilder getImageValueOrBuilder() {
      return imageValue_ == null ? tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceImageOuterClass.TextPieceImage.getDefaultInstance() : imageValue_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != false) {
        output.writeBool(1, type_);
      }
      if (format_ != null) {
        output.writeMessage(2, getFormat());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stringValue_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, stringValue_);
      }
      if (userValue_ != null) {
        output.writeMessage(4, getUserValue());
      }
      if (giftValue_ != null) {
        output.writeMessage(5, getGiftValue());
      }
      if (heartValue_ != null) {
        output.writeMessage(6, getHeartValue());
      }
      if (patternRefValue_ != null) {
        output.writeMessage(7, getPatternRefValue());
      }
      if (imageValue_ != null) {
        output.writeMessage(8, getImageValue());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, type_);
      }
      if (format_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getFormat());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stringValue_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, stringValue_);
      }
      if (userValue_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getUserValue());
      }
      if (giftValue_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getGiftValue());
      }
      if (heartValue_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getHeartValue());
      }
      if (patternRefValue_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getPatternRefValue());
      }
      if (imageValue_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getImageValue());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceOuterClass.TextPiece)) {
        return super.equals(obj);
      }
      tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceOuterClass.TextPiece other = (tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceOuterClass.TextPiece) obj;

      if (getType()
          != other.getType()) return false;
      if (hasFormat() != other.hasFormat()) return false;
      if (hasFormat()) {
        if (!getFormat()
            .equals(other.getFormat())) return false;
      }
      if (!getStringValue()
          .equals(other.getStringValue())) return false;
      if (hasUserValue() != other.hasUserValue()) return false;
      if (hasUserValue()) {
        if (!getUserValue()
            .equals(other.getUserValue())) return false;
      }
      if (hasGiftValue() != other.hasGiftValue()) return false;
      if (hasGiftValue()) {
        if (!getGiftValue()
            .equals(other.getGiftValue())) return false;
      }
      if (hasHeartValue() != other.hasHeartValue()) return false;
      if (hasHeartValue()) {
        if (!getHeartValue()
            .equals(other.getHeartValue())) return false;
      }
      if (hasPatternRefValue() != other.hasPatternRefValue()) return false;
      if (hasPatternRefValue()) {
        if (!getPatternRefValue()
            .equals(other.getPatternRefValue())) return false;
      }
      if (hasImageValue() != other.hasImageValue()) return false;
      if (hasImageValue()) {
        if (!getImageValue()
            .equals(other.getImageValue())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getType());
      if (hasFormat()) {
        hash = (37 * hash) + FORMAT_FIELD_NUMBER;
        hash = (53 * hash) + getFormat().hashCode();
      }
      hash = (37 * hash) + STRING_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getStringValue().hashCode();
      if (hasUserValue()) {
        hash = (37 * hash) + USER_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getUserValue().hashCode();
      }
      if (hasGiftValue()) {
        hash = (37 * hash) + GIFT_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getGiftValue().hashCode();
      }
      if (hasHeartValue()) {
        hash = (37 * hash) + HEART_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getHeartValue().hashCode();
      }
      if (hasPatternRefValue()) {
        hash = (37 * hash) + PATTERN_REF_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getPatternRefValue().hashCode();
      }
      if (hasImageValue()) {
        hash = (37 * hash) + IMAGE_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getImageValue().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceOuterClass.TextPiece parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceOuterClass.TextPiece parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceOuterClass.TextPiece parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceOuterClass.TextPiece parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceOuterClass.TextPiece parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceOuterClass.TextPiece parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceOuterClass.TextPiece parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceOuterClass.TextPiece parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceOuterClass.TextPiece parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceOuterClass.TextPiece parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceOuterClass.TextPiece parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceOuterClass.TextPiece parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceOuterClass.TextPiece prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TextPiece}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TextPiece)
        tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceOuterClass.TextPieceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceOuterClass.internal_static_TextPiece_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceOuterClass.internal_static_TextPiece_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceOuterClass.TextPiece.class, tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceOuterClass.TextPiece.Builder.class);
      }

      // Construct using tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceOuterClass.TextPiece.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        type_ = false;
        format_ = null;
        if (formatBuilder_ != null) {
          formatBuilder_.dispose();
          formatBuilder_ = null;
        }
        stringValue_ = "";
        userValue_ = null;
        if (userValueBuilder_ != null) {
          userValueBuilder_.dispose();
          userValueBuilder_ = null;
        }
        giftValue_ = null;
        if (giftValueBuilder_ != null) {
          giftValueBuilder_.dispose();
          giftValueBuilder_ = null;
        }
        heartValue_ = null;
        if (heartValueBuilder_ != null) {
          heartValueBuilder_.dispose();
          heartValueBuilder_ = null;
        }
        patternRefValue_ = null;
        if (patternRefValueBuilder_ != null) {
          patternRefValueBuilder_.dispose();
          patternRefValueBuilder_ = null;
        }
        imageValue_ = null;
        if (imageValueBuilder_ != null) {
          imageValueBuilder_.dispose();
          imageValueBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceOuterClass.internal_static_TextPiece_descriptor;
      }

      @java.lang.Override
      public tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceOuterClass.TextPiece getDefaultInstanceForType() {
        return tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceOuterClass.TextPiece.getDefaultInstance();
      }

      @java.lang.Override
      public tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceOuterClass.TextPiece build() {
        tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceOuterClass.TextPiece result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceOuterClass.TextPiece buildPartial() {
        tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceOuterClass.TextPiece result = new tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceOuterClass.TextPiece(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceOuterClass.TextPiece result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.type_ = type_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.format_ = formatBuilder_ == null
              ? format_
              : formatBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.stringValue_ = stringValue_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.userValue_ = userValueBuilder_ == null
              ? userValue_
              : userValueBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.giftValue_ = giftValueBuilder_ == null
              ? giftValue_
              : giftValueBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.heartValue_ = heartValueBuilder_ == null
              ? heartValue_
              : heartValueBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.patternRefValue_ = patternRefValueBuilder_ == null
              ? patternRefValue_
              : patternRefValueBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.imageValue_ = imageValueBuilder_ == null
              ? imageValue_
              : imageValueBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceOuterClass.TextPiece) {
          return mergeFrom((tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceOuterClass.TextPiece)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceOuterClass.TextPiece other) {
        if (other == tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceOuterClass.TextPiece.getDefaultInstance()) return this;
        if (other.getType() != false) {
          setType(other.getType());
        }
        if (other.hasFormat()) {
          mergeFormat(other.getFormat());
        }
        if (!other.getStringValue().isEmpty()) {
          stringValue_ = other.stringValue_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.hasUserValue()) {
          mergeUserValue(other.getUserValue());
        }
        if (other.hasGiftValue()) {
          mergeGiftValue(other.getGiftValue());
        }
        if (other.hasHeartValue()) {
          mergeHeartValue(other.getHeartValue());
        }
        if (other.hasPatternRefValue()) {
          mergePatternRefValue(other.getPatternRefValue());
        }
        if (other.hasImageValue()) {
          mergeImageValue(other.getImageValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                type_ = input.readBool();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                input.readMessage(
                    getFormatFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                stringValue_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                input.readMessage(
                    getUserValueFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                input.readMessage(
                    getGiftValueFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                input.readMessage(
                    getHeartValueFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                input.readMessage(
                    getPatternRefValueFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              case 66: {
                input.readMessage(
                    getImageValueFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000080;
                break;
              } // case 66
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private boolean type_ ;
      /**
       * <code>bool type = 1;</code>
       * @return The type.
       */
      @java.lang.Override
      public boolean getType() {
        return type_;
      }
      /**
       * <code>bool type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(boolean value) {

        type_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>bool type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = false;
        onChanged();
        return this;
      }

      private tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat format_;
      private com.google.protobuf.SingleFieldBuilderV3<
          tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat, tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat.Builder, tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormatOrBuilder> formatBuilder_;
      /**
       * <code>.TextFormat format = 2;</code>
       * @return Whether the format field is set.
       */
      public boolean hasFormat() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.TextFormat format = 2;</code>
       * @return The format.
       */
      public tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat getFormat() {
        if (formatBuilder_ == null) {
          return format_ == null ? tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat.getDefaultInstance() : format_;
        } else {
          return formatBuilder_.getMessage();
        }
      }
      /**
       * <code>.TextFormat format = 2;</code>
       */
      public Builder setFormat(tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat value) {
        if (formatBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          format_ = value;
        } else {
          formatBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.TextFormat format = 2;</code>
       */
      public Builder setFormat(
          tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat.Builder builderForValue) {
        if (formatBuilder_ == null) {
          format_ = builderForValue.build();
        } else {
          formatBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.TextFormat format = 2;</code>
       */
      public Builder mergeFormat(tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat value) {
        if (formatBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            format_ != null &&
            format_ != tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat.getDefaultInstance()) {
            getFormatBuilder().mergeFrom(value);
          } else {
            format_ = value;
          }
        } else {
          formatBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.TextFormat format = 2;</code>
       */
      public Builder clearFormat() {
        bitField0_ = (bitField0_ & ~0x00000002);
        format_ = null;
        if (formatBuilder_ != null) {
          formatBuilder_.dispose();
          formatBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.TextFormat format = 2;</code>
       */
      public tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat.Builder getFormatBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getFormatFieldBuilder().getBuilder();
      }
      /**
       * <code>.TextFormat format = 2;</code>
       */
      public tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormatOrBuilder getFormatOrBuilder() {
        if (formatBuilder_ != null) {
          return formatBuilder_.getMessageOrBuilder();
        } else {
          return format_ == null ?
              tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat.getDefaultInstance() : format_;
        }
      }
      /**
       * <code>.TextFormat format = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat, tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat.Builder, tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormatOrBuilder> 
          getFormatFieldBuilder() {
        if (formatBuilder_ == null) {
          formatBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat, tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat.Builder, tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormatOrBuilder>(
                  getFormat(),
                  getParentForChildren(),
                  isClean());
          format_ = null;
        }
        return formatBuilder_;
      }

      private java.lang.Object stringValue_ = "";
      /**
       * <code>string string_value = 3;</code>
       * @return The stringValue.
       */
      public java.lang.String getStringValue() {
        java.lang.Object ref = stringValue_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          stringValue_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string string_value = 3;</code>
       * @return The bytes for stringValue.
       */
      public com.google.protobuf.ByteString
          getStringValueBytes() {
        java.lang.Object ref = stringValue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stringValue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string string_value = 3;</code>
       * @param value The stringValue to set.
       * @return This builder for chaining.
       */
      public Builder setStringValue(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        stringValue_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string string_value = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearStringValue() {
        stringValue_ = getDefaultInstance().getStringValue();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string string_value = 3;</code>
       * @param value The bytes for stringValue to set.
       * @return This builder for chaining.
       */
      public Builder setStringValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        stringValue_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceUserOuterClass.TextPieceUser userValue_;
      private com.google.protobuf.SingleFieldBuilderV3<
          tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceUserOuterClass.TextPieceUser, tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceUserOuterClass.TextPieceUser.Builder, tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceUserOuterClass.TextPieceUserOrBuilder> userValueBuilder_;
      /**
       * <code>.TextPieceUser user_value = 4;</code>
       * @return Whether the userValue field is set.
       */
      public boolean hasUserValue() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>.TextPieceUser user_value = 4;</code>
       * @return The userValue.
       */
      public tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceUserOuterClass.TextPieceUser getUserValue() {
        if (userValueBuilder_ == null) {
          return userValue_ == null ? tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceUserOuterClass.TextPieceUser.getDefaultInstance() : userValue_;
        } else {
          return userValueBuilder_.getMessage();
        }
      }
      /**
       * <code>.TextPieceUser user_value = 4;</code>
       */
      public Builder setUserValue(tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceUserOuterClass.TextPieceUser value) {
        if (userValueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          userValue_ = value;
        } else {
          userValueBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.TextPieceUser user_value = 4;</code>
       */
      public Builder setUserValue(
          tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceUserOuterClass.TextPieceUser.Builder builderForValue) {
        if (userValueBuilder_ == null) {
          userValue_ = builderForValue.build();
        } else {
          userValueBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.TextPieceUser user_value = 4;</code>
       */
      public Builder mergeUserValue(tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceUserOuterClass.TextPieceUser value) {
        if (userValueBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
            userValue_ != null &&
            userValue_ != tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceUserOuterClass.TextPieceUser.getDefaultInstance()) {
            getUserValueBuilder().mergeFrom(value);
          } else {
            userValue_ = value;
          }
        } else {
          userValueBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.TextPieceUser user_value = 4;</code>
       */
      public Builder clearUserValue() {
        bitField0_ = (bitField0_ & ~0x00000008);
        userValue_ = null;
        if (userValueBuilder_ != null) {
          userValueBuilder_.dispose();
          userValueBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.TextPieceUser user_value = 4;</code>
       */
      public tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceUserOuterClass.TextPieceUser.Builder getUserValueBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getUserValueFieldBuilder().getBuilder();
      }
      /**
       * <code>.TextPieceUser user_value = 4;</code>
       */
      public tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceUserOuterClass.TextPieceUserOrBuilder getUserValueOrBuilder() {
        if (userValueBuilder_ != null) {
          return userValueBuilder_.getMessageOrBuilder();
        } else {
          return userValue_ == null ?
              tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceUserOuterClass.TextPieceUser.getDefaultInstance() : userValue_;
        }
      }
      /**
       * <code>.TextPieceUser user_value = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceUserOuterClass.TextPieceUser, tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceUserOuterClass.TextPieceUser.Builder, tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceUserOuterClass.TextPieceUserOrBuilder> 
          getUserValueFieldBuilder() {
        if (userValueBuilder_ == null) {
          userValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceUserOuterClass.TextPieceUser, tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceUserOuterClass.TextPieceUser.Builder, tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceUserOuterClass.TextPieceUserOrBuilder>(
                  getUserValue(),
                  getParentForChildren(),
                  isClean());
          userValue_ = null;
        }
        return userValueBuilder_;
      }

      private tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceGiftOuterClass.TextPieceGift giftValue_;
      private com.google.protobuf.SingleFieldBuilderV3<
          tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceGiftOuterClass.TextPieceGift, tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceGiftOuterClass.TextPieceGift.Builder, tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceGiftOuterClass.TextPieceGiftOrBuilder> giftValueBuilder_;
      /**
       * <code>.TextPieceGift gift_value = 5;</code>
       * @return Whether the giftValue field is set.
       */
      public boolean hasGiftValue() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>.TextPieceGift gift_value = 5;</code>
       * @return The giftValue.
       */
      public tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceGiftOuterClass.TextPieceGift getGiftValue() {
        if (giftValueBuilder_ == null) {
          return giftValue_ == null ? tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceGiftOuterClass.TextPieceGift.getDefaultInstance() : giftValue_;
        } else {
          return giftValueBuilder_.getMessage();
        }
      }
      /**
       * <code>.TextPieceGift gift_value = 5;</code>
       */
      public Builder setGiftValue(tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceGiftOuterClass.TextPieceGift value) {
        if (giftValueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          giftValue_ = value;
        } else {
          giftValueBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.TextPieceGift gift_value = 5;</code>
       */
      public Builder setGiftValue(
          tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceGiftOuterClass.TextPieceGift.Builder builderForValue) {
        if (giftValueBuilder_ == null) {
          giftValue_ = builderForValue.build();
        } else {
          giftValueBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.TextPieceGift gift_value = 5;</code>
       */
      public Builder mergeGiftValue(tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceGiftOuterClass.TextPieceGift value) {
        if (giftValueBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0) &&
            giftValue_ != null &&
            giftValue_ != tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceGiftOuterClass.TextPieceGift.getDefaultInstance()) {
            getGiftValueBuilder().mergeFrom(value);
          } else {
            giftValue_ = value;
          }
        } else {
          giftValueBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.TextPieceGift gift_value = 5;</code>
       */
      public Builder clearGiftValue() {
        bitField0_ = (bitField0_ & ~0x00000010);
        giftValue_ = null;
        if (giftValueBuilder_ != null) {
          giftValueBuilder_.dispose();
          giftValueBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.TextPieceGift gift_value = 5;</code>
       */
      public tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceGiftOuterClass.TextPieceGift.Builder getGiftValueBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getGiftValueFieldBuilder().getBuilder();
      }
      /**
       * <code>.TextPieceGift gift_value = 5;</code>
       */
      public tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceGiftOuterClass.TextPieceGiftOrBuilder getGiftValueOrBuilder() {
        if (giftValueBuilder_ != null) {
          return giftValueBuilder_.getMessageOrBuilder();
        } else {
          return giftValue_ == null ?
              tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceGiftOuterClass.TextPieceGift.getDefaultInstance() : giftValue_;
        }
      }
      /**
       * <code>.TextPieceGift gift_value = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceGiftOuterClass.TextPieceGift, tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceGiftOuterClass.TextPieceGift.Builder, tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceGiftOuterClass.TextPieceGiftOrBuilder> 
          getGiftValueFieldBuilder() {
        if (giftValueBuilder_ == null) {
          giftValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceGiftOuterClass.TextPieceGift, tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceGiftOuterClass.TextPieceGift.Builder, tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceGiftOuterClass.TextPieceGiftOrBuilder>(
                  getGiftValue(),
                  getParentForChildren(),
                  isClean());
          giftValue_ = null;
        }
        return giftValueBuilder_;
      }

      private tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceHeartOuterClass.TextPieceHeart heartValue_;
      private com.google.protobuf.SingleFieldBuilderV3<
          tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceHeartOuterClass.TextPieceHeart, tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceHeartOuterClass.TextPieceHeart.Builder, tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceHeartOuterClass.TextPieceHeartOrBuilder> heartValueBuilder_;
      /**
       * <code>.TextPieceHeart heart_value = 6;</code>
       * @return Whether the heartValue field is set.
       */
      public boolean hasHeartValue() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>.TextPieceHeart heart_value = 6;</code>
       * @return The heartValue.
       */
      public tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceHeartOuterClass.TextPieceHeart getHeartValue() {
        if (heartValueBuilder_ == null) {
          return heartValue_ == null ? tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceHeartOuterClass.TextPieceHeart.getDefaultInstance() : heartValue_;
        } else {
          return heartValueBuilder_.getMessage();
        }
      }
      /**
       * <code>.TextPieceHeart heart_value = 6;</code>
       */
      public Builder setHeartValue(tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceHeartOuterClass.TextPieceHeart value) {
        if (heartValueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          heartValue_ = value;
        } else {
          heartValueBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>.TextPieceHeart heart_value = 6;</code>
       */
      public Builder setHeartValue(
          tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceHeartOuterClass.TextPieceHeart.Builder builderForValue) {
        if (heartValueBuilder_ == null) {
          heartValue_ = builderForValue.build();
        } else {
          heartValueBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>.TextPieceHeart heart_value = 6;</code>
       */
      public Builder mergeHeartValue(tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceHeartOuterClass.TextPieceHeart value) {
        if (heartValueBuilder_ == null) {
          if (((bitField0_ & 0x00000020) != 0) &&
            heartValue_ != null &&
            heartValue_ != tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceHeartOuterClass.TextPieceHeart.getDefaultInstance()) {
            getHeartValueBuilder().mergeFrom(value);
          } else {
            heartValue_ = value;
          }
        } else {
          heartValueBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>.TextPieceHeart heart_value = 6;</code>
       */
      public Builder clearHeartValue() {
        bitField0_ = (bitField0_ & ~0x00000020);
        heartValue_ = null;
        if (heartValueBuilder_ != null) {
          heartValueBuilder_.dispose();
          heartValueBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.TextPieceHeart heart_value = 6;</code>
       */
      public tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceHeartOuterClass.TextPieceHeart.Builder getHeartValueBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getHeartValueFieldBuilder().getBuilder();
      }
      /**
       * <code>.TextPieceHeart heart_value = 6;</code>
       */
      public tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceHeartOuterClass.TextPieceHeartOrBuilder getHeartValueOrBuilder() {
        if (heartValueBuilder_ != null) {
          return heartValueBuilder_.getMessageOrBuilder();
        } else {
          return heartValue_ == null ?
              tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceHeartOuterClass.TextPieceHeart.getDefaultInstance() : heartValue_;
        }
      }
      /**
       * <code>.TextPieceHeart heart_value = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceHeartOuterClass.TextPieceHeart, tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceHeartOuterClass.TextPieceHeart.Builder, tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceHeartOuterClass.TextPieceHeartOrBuilder> 
          getHeartValueFieldBuilder() {
        if (heartValueBuilder_ == null) {
          heartValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceHeartOuterClass.TextPieceHeart, tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceHeartOuterClass.TextPieceHeart.Builder, tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceHeartOuterClass.TextPieceHeartOrBuilder>(
                  getHeartValue(),
                  getParentForChildren(),
                  isClean());
          heartValue_ = null;
        }
        return heartValueBuilder_;
      }

      private tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPiecePatternRefOuterClass.TextPiecePatternRef patternRefValue_;
      private com.google.protobuf.SingleFieldBuilderV3<
          tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPiecePatternRefOuterClass.TextPiecePatternRef, tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPiecePatternRefOuterClass.TextPiecePatternRef.Builder, tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPiecePatternRefOuterClass.TextPiecePatternRefOrBuilder> patternRefValueBuilder_;
      /**
       * <code>.TextPiecePatternRef pattern_ref_value = 7;</code>
       * @return Whether the patternRefValue field is set.
       */
      public boolean hasPatternRefValue() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>.TextPiecePatternRef pattern_ref_value = 7;</code>
       * @return The patternRefValue.
       */
      public tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPiecePatternRefOuterClass.TextPiecePatternRef getPatternRefValue() {
        if (patternRefValueBuilder_ == null) {
          return patternRefValue_ == null ? tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPiecePatternRefOuterClass.TextPiecePatternRef.getDefaultInstance() : patternRefValue_;
        } else {
          return patternRefValueBuilder_.getMessage();
        }
      }
      /**
       * <code>.TextPiecePatternRef pattern_ref_value = 7;</code>
       */
      public Builder setPatternRefValue(tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPiecePatternRefOuterClass.TextPiecePatternRef value) {
        if (patternRefValueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          patternRefValue_ = value;
        } else {
          patternRefValueBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>.TextPiecePatternRef pattern_ref_value = 7;</code>
       */
      public Builder setPatternRefValue(
          tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPiecePatternRefOuterClass.TextPiecePatternRef.Builder builderForValue) {
        if (patternRefValueBuilder_ == null) {
          patternRefValue_ = builderForValue.build();
        } else {
          patternRefValueBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>.TextPiecePatternRef pattern_ref_value = 7;</code>
       */
      public Builder mergePatternRefValue(tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPiecePatternRefOuterClass.TextPiecePatternRef value) {
        if (patternRefValueBuilder_ == null) {
          if (((bitField0_ & 0x00000040) != 0) &&
            patternRefValue_ != null &&
            patternRefValue_ != tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPiecePatternRefOuterClass.TextPiecePatternRef.getDefaultInstance()) {
            getPatternRefValueBuilder().mergeFrom(value);
          } else {
            patternRefValue_ = value;
          }
        } else {
          patternRefValueBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>.TextPiecePatternRef pattern_ref_value = 7;</code>
       */
      public Builder clearPatternRefValue() {
        bitField0_ = (bitField0_ & ~0x00000040);
        patternRefValue_ = null;
        if (patternRefValueBuilder_ != null) {
          patternRefValueBuilder_.dispose();
          patternRefValueBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.TextPiecePatternRef pattern_ref_value = 7;</code>
       */
      public tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPiecePatternRefOuterClass.TextPiecePatternRef.Builder getPatternRefValueBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return getPatternRefValueFieldBuilder().getBuilder();
      }
      /**
       * <code>.TextPiecePatternRef pattern_ref_value = 7;</code>
       */
      public tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPiecePatternRefOuterClass.TextPiecePatternRefOrBuilder getPatternRefValueOrBuilder() {
        if (patternRefValueBuilder_ != null) {
          return patternRefValueBuilder_.getMessageOrBuilder();
        } else {
          return patternRefValue_ == null ?
              tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPiecePatternRefOuterClass.TextPiecePatternRef.getDefaultInstance() : patternRefValue_;
        }
      }
      /**
       * <code>.TextPiecePatternRef pattern_ref_value = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPiecePatternRefOuterClass.TextPiecePatternRef, tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPiecePatternRefOuterClass.TextPiecePatternRef.Builder, tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPiecePatternRefOuterClass.TextPiecePatternRefOrBuilder> 
          getPatternRefValueFieldBuilder() {
        if (patternRefValueBuilder_ == null) {
          patternRefValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPiecePatternRefOuterClass.TextPiecePatternRef, tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPiecePatternRefOuterClass.TextPiecePatternRef.Builder, tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPiecePatternRefOuterClass.TextPiecePatternRefOrBuilder>(
                  getPatternRefValue(),
                  getParentForChildren(),
                  isClean());
          patternRefValue_ = null;
        }
        return patternRefValueBuilder_;
      }

      private tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceImageOuterClass.TextPieceImage imageValue_;
      private com.google.protobuf.SingleFieldBuilderV3<
          tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceImageOuterClass.TextPieceImage, tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceImageOuterClass.TextPieceImage.Builder, tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceImageOuterClass.TextPieceImageOrBuilder> imageValueBuilder_;
      /**
       * <code>.TextPieceImage image_value = 8;</code>
       * @return Whether the imageValue field is set.
       */
      public boolean hasImageValue() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <code>.TextPieceImage image_value = 8;</code>
       * @return The imageValue.
       */
      public tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceImageOuterClass.TextPieceImage getImageValue() {
        if (imageValueBuilder_ == null) {
          return imageValue_ == null ? tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceImageOuterClass.TextPieceImage.getDefaultInstance() : imageValue_;
        } else {
          return imageValueBuilder_.getMessage();
        }
      }
      /**
       * <code>.TextPieceImage image_value = 8;</code>
       */
      public Builder setImageValue(tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceImageOuterClass.TextPieceImage value) {
        if (imageValueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          imageValue_ = value;
        } else {
          imageValueBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>.TextPieceImage image_value = 8;</code>
       */
      public Builder setImageValue(
          tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceImageOuterClass.TextPieceImage.Builder builderForValue) {
        if (imageValueBuilder_ == null) {
          imageValue_ = builderForValue.build();
        } else {
          imageValueBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>.TextPieceImage image_value = 8;</code>
       */
      public Builder mergeImageValue(tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceImageOuterClass.TextPieceImage value) {
        if (imageValueBuilder_ == null) {
          if (((bitField0_ & 0x00000080) != 0) &&
            imageValue_ != null &&
            imageValue_ != tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceImageOuterClass.TextPieceImage.getDefaultInstance()) {
            getImageValueBuilder().mergeFrom(value);
          } else {
            imageValue_ = value;
          }
        } else {
          imageValueBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>.TextPieceImage image_value = 8;</code>
       */
      public Builder clearImageValue() {
        bitField0_ = (bitField0_ & ~0x00000080);
        imageValue_ = null;
        if (imageValueBuilder_ != null) {
          imageValueBuilder_.dispose();
          imageValueBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.TextPieceImage image_value = 8;</code>
       */
      public tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceImageOuterClass.TextPieceImage.Builder getImageValueBuilder() {
        bitField0_ |= 0x00000080;
        onChanged();
        return getImageValueFieldBuilder().getBuilder();
      }
      /**
       * <code>.TextPieceImage image_value = 8;</code>
       */
      public tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceImageOuterClass.TextPieceImageOrBuilder getImageValueOrBuilder() {
        if (imageValueBuilder_ != null) {
          return imageValueBuilder_.getMessageOrBuilder();
        } else {
          return imageValue_ == null ?
              tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceImageOuterClass.TextPieceImage.getDefaultInstance() : imageValue_;
        }
      }
      /**
       * <code>.TextPieceImage image_value = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceImageOuterClass.TextPieceImage, tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceImageOuterClass.TextPieceImage.Builder, tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceImageOuterClass.TextPieceImageOrBuilder> 
          getImageValueFieldBuilder() {
        if (imageValueBuilder_ == null) {
          imageValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceImageOuterClass.TextPieceImage, tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceImageOuterClass.TextPieceImage.Builder, tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceImageOuterClass.TextPieceImageOrBuilder>(
                  getImageValue(),
                  getParentForChildren(),
                  isClean());
          imageValue_ = null;
        }
        return imageValueBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TextPiece)
    }

    // @@protoc_insertion_point(class_scope:TextPiece)
    private static final tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceOuterClass.TextPiece DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceOuterClass.TextPiece();
    }

    public static tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceOuterClass.TextPiece getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TextPiece>
        PARSER = new com.google.protobuf.AbstractParser<TextPiece>() {
      @java.lang.Override
      public TextPiece parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TextPiece> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TextPiece> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceOuterClass.TextPiece getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TextPiece_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TextPiece_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017TextPiece.proto\032\020TextFormat.proto\032\024Tex" +
      "tPieceImage.proto\032\031TextPiecePatternRef.p" +
      "roto\032\024TextPieceHeart.proto\032\023TextPieceGif" +
      "t.proto\032\023TextPieceUser.proto\"\221\002\n\tTextPie" +
      "ce\022\014\n\004type\030\001 \001(\010\022\033\n\006format\030\002 \001(\0132\013.TextF" +
      "ormat\022\024\n\014string_value\030\003 \001(\t\022\"\n\nuser_valu" +
      "e\030\004 \001(\0132\016.TextPieceUser\022\"\n\ngift_value\030\005 " +
      "\001(\0132\016.TextPieceGift\022$\n\013heart_value\030\006 \001(\013" +
      "2\017.TextPieceHeart\022/\n\021pattern_ref_value\030\007" +
      " \001(\0132\024.TextPiecePatternRef\022$\n\013image_valu" +
      "e\030\010 \001(\0132\017.TextPieceImageB8\n6tech.ordinar" +
      "yroad.live.chat.client.douyin.protobuf.d" +
      "tob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.getDescriptor(),
          tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceImageOuterClass.getDescriptor(),
          tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPiecePatternRefOuterClass.getDescriptor(),
          tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceHeartOuterClass.getDescriptor(),
          tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceGiftOuterClass.getDescriptor(),
          tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceUserOuterClass.getDescriptor(),
        });
    internal_static_TextPiece_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TextPiece_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TextPiece_descriptor,
        new java.lang.String[] { "Type", "Format", "StringValue", "UserValue", "GiftValue", "HeartValue", "PatternRefValue", "ImageValue", });
    tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.getDescriptor();
    tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceImageOuterClass.getDescriptor();
    tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPiecePatternRefOuterClass.getDescriptor();
    tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceHeartOuterClass.getDescriptor();
    tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceGiftOuterClass.getDescriptor();
    tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextPieceUserOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
