/*
 * MIT License
 *
 * Copyright (c) 2023 OrdinaryRoad
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TextFormat.proto

package tech.ordinaryroad.live.chat.client.douyin.protobuf.dto;

public final class TextFormatOuterClass {
  private TextFormatOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TextFormatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TextFormat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string color = 1;</code>
     * @return The color.
     */
    java.lang.String getColor();
    /**
     * <code>string color = 1;</code>
     * @return The bytes for color.
     */
    com.google.protobuf.ByteString
        getColorBytes();

    /**
     * <code>bool bold = 2;</code>
     * @return The bold.
     */
    boolean getBold();

    /**
     * <code>bool italic = 3;</code>
     * @return The italic.
     */
    boolean getItalic();

    /**
     * <code>uint32 weight = 4;</code>
     * @return The weight.
     */
    int getWeight();

    /**
     * <code>uint32 italic_angle = 5;</code>
     * @return The italicAngle.
     */
    int getItalicAngle();

    /**
     * <code>uint32 font_size = 6;</code>
     * @return The fontSize.
     */
    int getFontSize();

    /**
     * <code>bool use_heigh_light_color = 7;</code>
     * @return The useHeighLightColor.
     */
    boolean getUseHeighLightColor();

    /**
     * <code>bool use_remote_clor = 8;</code>
     * @return The useRemoteClor.
     */
    boolean getUseRemoteClor();
  }
  /**
   * Protobuf type {@code TextFormat}
   */
  public static final class TextFormat extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TextFormat)
      TextFormatOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TextFormat.newBuilder() to construct.
    private TextFormat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TextFormat() {
      color_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TextFormat();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.internal_static_TextFormat_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.internal_static_TextFormat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat.class, tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat.Builder.class);
    }

    public static final int COLOR_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object color_ = "";
    /**
     * <code>string color = 1;</code>
     * @return The color.
     */
    @java.lang.Override
    public java.lang.String getColor() {
      java.lang.Object ref = color_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        color_ = s;
        return s;
      }
    }
    /**
     * <code>string color = 1;</code>
     * @return The bytes for color.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getColorBytes() {
      java.lang.Object ref = color_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        color_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BOLD_FIELD_NUMBER = 2;
    private boolean bold_ = false;
    /**
     * <code>bool bold = 2;</code>
     * @return The bold.
     */
    @java.lang.Override
    public boolean getBold() {
      return bold_;
    }

    public static final int ITALIC_FIELD_NUMBER = 3;
    private boolean italic_ = false;
    /**
     * <code>bool italic = 3;</code>
     * @return The italic.
     */
    @java.lang.Override
    public boolean getItalic() {
      return italic_;
    }

    public static final int WEIGHT_FIELD_NUMBER = 4;
    private int weight_ = 0;
    /**
     * <code>uint32 weight = 4;</code>
     * @return The weight.
     */
    @java.lang.Override
    public int getWeight() {
      return weight_;
    }

    public static final int ITALIC_ANGLE_FIELD_NUMBER = 5;
    private int italicAngle_ = 0;
    /**
     * <code>uint32 italic_angle = 5;</code>
     * @return The italicAngle.
     */
    @java.lang.Override
    public int getItalicAngle() {
      return italicAngle_;
    }

    public static final int FONT_SIZE_FIELD_NUMBER = 6;
    private int fontSize_ = 0;
    /**
     * <code>uint32 font_size = 6;</code>
     * @return The fontSize.
     */
    @java.lang.Override
    public int getFontSize() {
      return fontSize_;
    }

    public static final int USE_HEIGH_LIGHT_COLOR_FIELD_NUMBER = 7;
    private boolean useHeighLightColor_ = false;
    /**
     * <code>bool use_heigh_light_color = 7;</code>
     * @return The useHeighLightColor.
     */
    @java.lang.Override
    public boolean getUseHeighLightColor() {
      return useHeighLightColor_;
    }

    public static final int USE_REMOTE_CLOR_FIELD_NUMBER = 8;
    private boolean useRemoteClor_ = false;
    /**
     * <code>bool use_remote_clor = 8;</code>
     * @return The useRemoteClor.
     */
    @java.lang.Override
    public boolean getUseRemoteClor() {
      return useRemoteClor_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(color_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, color_);
      }
      if (bold_ != false) {
        output.writeBool(2, bold_);
      }
      if (italic_ != false) {
        output.writeBool(3, italic_);
      }
      if (weight_ != 0) {
        output.writeUInt32(4, weight_);
      }
      if (italicAngle_ != 0) {
        output.writeUInt32(5, italicAngle_);
      }
      if (fontSize_ != 0) {
        output.writeUInt32(6, fontSize_);
      }
      if (useHeighLightColor_ != false) {
        output.writeBool(7, useHeighLightColor_);
      }
      if (useRemoteClor_ != false) {
        output.writeBool(8, useRemoteClor_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(color_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, color_);
      }
      if (bold_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, bold_);
      }
      if (italic_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, italic_);
      }
      if (weight_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, weight_);
      }
      if (italicAngle_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, italicAngle_);
      }
      if (fontSize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, fontSize_);
      }
      if (useHeighLightColor_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, useHeighLightColor_);
      }
      if (useRemoteClor_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, useRemoteClor_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat)) {
        return super.equals(obj);
      }
      tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat other = (tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat) obj;

      if (!getColor()
          .equals(other.getColor())) return false;
      if (getBold()
          != other.getBold()) return false;
      if (getItalic()
          != other.getItalic()) return false;
      if (getWeight()
          != other.getWeight()) return false;
      if (getItalicAngle()
          != other.getItalicAngle()) return false;
      if (getFontSize()
          != other.getFontSize()) return false;
      if (getUseHeighLightColor()
          != other.getUseHeighLightColor()) return false;
      if (getUseRemoteClor()
          != other.getUseRemoteClor()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + COLOR_FIELD_NUMBER;
      hash = (53 * hash) + getColor().hashCode();
      hash = (37 * hash) + BOLD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getBold());
      hash = (37 * hash) + ITALIC_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getItalic());
      hash = (37 * hash) + WEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + getWeight();
      hash = (37 * hash) + ITALIC_ANGLE_FIELD_NUMBER;
      hash = (53 * hash) + getItalicAngle();
      hash = (37 * hash) + FONT_SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getFontSize();
      hash = (37 * hash) + USE_HEIGH_LIGHT_COLOR_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getUseHeighLightColor());
      hash = (37 * hash) + USE_REMOTE_CLOR_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getUseRemoteClor());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TextFormat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TextFormat)
        tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.internal_static_TextFormat_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.internal_static_TextFormat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat.class, tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat.Builder.class);
      }

      // Construct using tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        color_ = "";
        bold_ = false;
        italic_ = false;
        weight_ = 0;
        italicAngle_ = 0;
        fontSize_ = 0;
        useHeighLightColor_ = false;
        useRemoteClor_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.internal_static_TextFormat_descriptor;
      }

      @java.lang.Override
      public tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat getDefaultInstanceForType() {
        return tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat.getDefaultInstance();
      }

      @java.lang.Override
      public tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat build() {
        tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat buildPartial() {
        tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat result = new tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.color_ = color_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.bold_ = bold_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.italic_ = italic_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.weight_ = weight_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.italicAngle_ = italicAngle_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.fontSize_ = fontSize_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.useHeighLightColor_ = useHeighLightColor_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.useRemoteClor_ = useRemoteClor_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat) {
          return mergeFrom((tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat other) {
        if (other == tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat.getDefaultInstance()) return this;
        if (!other.getColor().isEmpty()) {
          color_ = other.color_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getBold() != false) {
          setBold(other.getBold());
        }
        if (other.getItalic() != false) {
          setItalic(other.getItalic());
        }
        if (other.getWeight() != 0) {
          setWeight(other.getWeight());
        }
        if (other.getItalicAngle() != 0) {
          setItalicAngle(other.getItalicAngle());
        }
        if (other.getFontSize() != 0) {
          setFontSize(other.getFontSize());
        }
        if (other.getUseHeighLightColor() != false) {
          setUseHeighLightColor(other.getUseHeighLightColor());
        }
        if (other.getUseRemoteClor() != false) {
          setUseRemoteClor(other.getUseRemoteClor());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                color_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                bold_ = input.readBool();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                italic_ = input.readBool();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                weight_ = input.readUInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                italicAngle_ = input.readUInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                fontSize_ = input.readUInt32();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 56: {
                useHeighLightColor_ = input.readBool();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              case 64: {
                useRemoteClor_ = input.readBool();
                bitField0_ |= 0x00000080;
                break;
              } // case 64
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object color_ = "";
      /**
       * <code>string color = 1;</code>
       * @return The color.
       */
      public java.lang.String getColor() {
        java.lang.Object ref = color_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          color_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string color = 1;</code>
       * @return The bytes for color.
       */
      public com.google.protobuf.ByteString
          getColorBytes() {
        java.lang.Object ref = color_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          color_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string color = 1;</code>
       * @param value The color to set.
       * @return This builder for chaining.
       */
      public Builder setColor(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        color_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string color = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearColor() {
        color_ = getDefaultInstance().getColor();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string color = 1;</code>
       * @param value The bytes for color to set.
       * @return This builder for chaining.
       */
      public Builder setColorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        color_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private boolean bold_ ;
      /**
       * <code>bool bold = 2;</code>
       * @return The bold.
       */
      @java.lang.Override
      public boolean getBold() {
        return bold_;
      }
      /**
       * <code>bool bold = 2;</code>
       * @param value The bold to set.
       * @return This builder for chaining.
       */
      public Builder setBold(boolean value) {

        bold_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>bool bold = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBold() {
        bitField0_ = (bitField0_ & ~0x00000002);
        bold_ = false;
        onChanged();
        return this;
      }

      private boolean italic_ ;
      /**
       * <code>bool italic = 3;</code>
       * @return The italic.
       */
      @java.lang.Override
      public boolean getItalic() {
        return italic_;
      }
      /**
       * <code>bool italic = 3;</code>
       * @param value The italic to set.
       * @return This builder for chaining.
       */
      public Builder setItalic(boolean value) {

        italic_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bool italic = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearItalic() {
        bitField0_ = (bitField0_ & ~0x00000004);
        italic_ = false;
        onChanged();
        return this;
      }

      private int weight_ ;
      /**
       * <code>uint32 weight = 4;</code>
       * @return The weight.
       */
      @java.lang.Override
      public int getWeight() {
        return weight_;
      }
      /**
       * <code>uint32 weight = 4;</code>
       * @param value The weight to set.
       * @return This builder for chaining.
       */
      public Builder setWeight(int value) {

        weight_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 weight = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearWeight() {
        bitField0_ = (bitField0_ & ~0x00000008);
        weight_ = 0;
        onChanged();
        return this;
      }

      private int italicAngle_ ;
      /**
       * <code>uint32 italic_angle = 5;</code>
       * @return The italicAngle.
       */
      @java.lang.Override
      public int getItalicAngle() {
        return italicAngle_;
      }
      /**
       * <code>uint32 italic_angle = 5;</code>
       * @param value The italicAngle to set.
       * @return This builder for chaining.
       */
      public Builder setItalicAngle(int value) {

        italicAngle_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 italic_angle = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearItalicAngle() {
        bitField0_ = (bitField0_ & ~0x00000010);
        italicAngle_ = 0;
        onChanged();
        return this;
      }

      private int fontSize_ ;
      /**
       * <code>uint32 font_size = 6;</code>
       * @return The fontSize.
       */
      @java.lang.Override
      public int getFontSize() {
        return fontSize_;
      }
      /**
       * <code>uint32 font_size = 6;</code>
       * @param value The fontSize to set.
       * @return This builder for chaining.
       */
      public Builder setFontSize(int value) {

        fontSize_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 font_size = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearFontSize() {
        bitField0_ = (bitField0_ & ~0x00000020);
        fontSize_ = 0;
        onChanged();
        return this;
      }

      private boolean useHeighLightColor_ ;
      /**
       * <code>bool use_heigh_light_color = 7;</code>
       * @return The useHeighLightColor.
       */
      @java.lang.Override
      public boolean getUseHeighLightColor() {
        return useHeighLightColor_;
      }
      /**
       * <code>bool use_heigh_light_color = 7;</code>
       * @param value The useHeighLightColor to set.
       * @return This builder for chaining.
       */
      public Builder setUseHeighLightColor(boolean value) {

        useHeighLightColor_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>bool use_heigh_light_color = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearUseHeighLightColor() {
        bitField0_ = (bitField0_ & ~0x00000040);
        useHeighLightColor_ = false;
        onChanged();
        return this;
      }

      private boolean useRemoteClor_ ;
      /**
       * <code>bool use_remote_clor = 8;</code>
       * @return The useRemoteClor.
       */
      @java.lang.Override
      public boolean getUseRemoteClor() {
        return useRemoteClor_;
      }
      /**
       * <code>bool use_remote_clor = 8;</code>
       * @param value The useRemoteClor to set.
       * @return This builder for chaining.
       */
      public Builder setUseRemoteClor(boolean value) {

        useRemoteClor_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>bool use_remote_clor = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearUseRemoteClor() {
        bitField0_ = (bitField0_ & ~0x00000080);
        useRemoteClor_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TextFormat)
    }

    // @@protoc_insertion_point(class_scope:TextFormat)
    private static final tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat();
    }

    public static tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TextFormat>
        PARSER = new com.google.protobuf.AbstractParser<TextFormat>() {
      @java.lang.Override
      public TextFormat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TextFormat> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TextFormat> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.TextFormatOuterClass.TextFormat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TextFormat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TextFormat_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020TextFormat.proto\"\252\001\n\nTextFormat\022\r\n\005col" +
      "or\030\001 \001(\t\022\014\n\004bold\030\002 \001(\010\022\016\n\006italic\030\003 \001(\010\022\016" +
      "\n\006weight\030\004 \001(\r\022\024\n\014italic_angle\030\005 \001(\r\022\021\n\t" +
      "font_size\030\006 \001(\r\022\035\n\025use_heigh_light_color" +
      "\030\007 \001(\010\022\027\n\017use_remote_clor\030\010 \001(\010B8\n6tech." +
      "ordinaryroad.live.chat.client.douyin.pro" +
      "tobuf.dtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_TextFormat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TextFormat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TextFormat_descriptor,
        new java.lang.String[] { "Color", "Bold", "Italic", "Weight", "ItalicAngle", "FontSize", "UseHeighLightColor", "UseRemoteClor", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
