/*
 * MIT License
 *
 * Copyright (c) 2023 OrdinaryRoad
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LiveAudienceState.proto

package tech.ordinaryroad.live.chat.client.kuaishou.protobuf;

public final class LiveAudienceStateOuterClass {
  private LiveAudienceStateOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LiveAudienceStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LiveAudienceState)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool isFromFansTop = 1;</code>
     * @return The isFromFansTop.
     */
    boolean getIsFromFansTop();

    /**
     * <code>bool isKoi = 2;</code>
     * @return The isKoi.
     */
    boolean getIsKoi();

    /**
     * <code>.LiveAudienceState.AssistantType assistantType = 3;</code>
     * @return The enum numeric value on the wire for assistantType.
     */
    int getAssistantTypeValue();
    /**
     * <code>.LiveAudienceState.AssistantType assistantType = 3;</code>
     * @return The assistantType.
     */
    tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState.AssistantType getAssistantType();

    /**
     * <code>uint32 fansGroupIntimacyLevel = 4;</code>
     * @return The fansGroupIntimacyLevel.
     */
    int getFansGroupIntimacyLevel();

    /**
     * <code>.GzoneNameplate nameplate = 5;</code>
     * @return Whether the nameplate field is set.
     */
    boolean hasNameplate();
    /**
     * <code>.GzoneNameplate nameplate = 5;</code>
     * @return The nameplate.
     */
    tech.ordinaryroad.live.chat.client.kuaishou.protobuf.GzoneNameplateOuterClass.GzoneNameplate getNameplate();
    /**
     * <code>.GzoneNameplate nameplate = 5;</code>
     */
    tech.ordinaryroad.live.chat.client.kuaishou.protobuf.GzoneNameplateOuterClass.GzoneNameplateOrBuilder getNameplateOrBuilder();

    /**
     * <code>.LiveFansGroupState liveFansGroupState = 6;</code>
     * @return Whether the liveFansGroupState field is set.
     */
    boolean hasLiveFansGroupState();
    /**
     * <code>.LiveFansGroupState liveFansGroupState = 6;</code>
     * @return The liveFansGroupState.
     */
    tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveFansGroupStateOuterClass.LiveFansGroupState getLiveFansGroupState();
    /**
     * <code>.LiveFansGroupState liveFansGroupState = 6;</code>
     */
    tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveFansGroupStateOuterClass.LiveFansGroupStateOrBuilder getLiveFansGroupStateOrBuilder();

    /**
     * <code>uint32 wealthGrade = 7;</code>
     * @return The wealthGrade.
     */
    int getWealthGrade();

    /**
     * <code>string badgeKey = 8;</code>
     * @return The badgeKey.
     */
    java.lang.String getBadgeKey();
    /**
     * <code>string badgeKey = 8;</code>
     * @return The bytes for badgeKey.
     */
    com.google.protobuf.ByteString
        getBadgeKeyBytes();
  }
  /**
   * Protobuf type {@code LiveAudienceState}
   */
  public static final class LiveAudienceState extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LiveAudienceState)
      LiveAudienceStateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LiveAudienceState.newBuilder() to construct.
    private LiveAudienceState(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LiveAudienceState() {
      assistantType_ = 0;
      badgeKey_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LiveAudienceState();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.internal_static_LiveAudienceState_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.internal_static_LiveAudienceState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState.class, tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState.Builder.class);
    }

    /**
     * Protobuf enum {@code LiveAudienceState.AssistantType}
     */
    public enum AssistantType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN_ASSISTANT_TYPE = 0;</code>
       */
      UNKNOWN_ASSISTANT_TYPE(0),
      /**
       * <code>SUPER = 1;</code>
       */
      SUPER(1),
      /**
       * <code>JUNIOR = 2;</code>
       */
      JUNIOR(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNKNOWN_ASSISTANT_TYPE = 0;</code>
       */
      public static final int UNKNOWN_ASSISTANT_TYPE_VALUE = 0;
      /**
       * <code>SUPER = 1;</code>
       */
      public static final int SUPER_VALUE = 1;
      /**
       * <code>JUNIOR = 2;</code>
       */
      public static final int JUNIOR_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static AssistantType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static AssistantType forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN_ASSISTANT_TYPE;
          case 1: return SUPER;
          case 2: return JUNIOR;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<AssistantType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          AssistantType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<AssistantType>() {
              public AssistantType findValueByNumber(int number) {
                return AssistantType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState.getDescriptor().getEnumTypes().get(0);
      }

      private static final AssistantType[] VALUES = values();

      public static AssistantType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private AssistantType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:LiveAudienceState.AssistantType)
    }

    public static final int ISFROMFANSTOP_FIELD_NUMBER = 1;
    private boolean isFromFansTop_ = false;
    /**
     * <code>bool isFromFansTop = 1;</code>
     * @return The isFromFansTop.
     */
    @java.lang.Override
    public boolean getIsFromFansTop() {
      return isFromFansTop_;
    }

    public static final int ISKOI_FIELD_NUMBER = 2;
    private boolean isKoi_ = false;
    /**
     * <code>bool isKoi = 2;</code>
     * @return The isKoi.
     */
    @java.lang.Override
    public boolean getIsKoi() {
      return isKoi_;
    }

    public static final int ASSISTANTTYPE_FIELD_NUMBER = 3;
    private int assistantType_ = 0;
    /**
     * <code>.LiveAudienceState.AssistantType assistantType = 3;</code>
     * @return The enum numeric value on the wire for assistantType.
     */
    @java.lang.Override public int getAssistantTypeValue() {
      return assistantType_;
    }
    /**
     * <code>.LiveAudienceState.AssistantType assistantType = 3;</code>
     * @return The assistantType.
     */
    @java.lang.Override public tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState.AssistantType getAssistantType() {
      tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState.AssistantType result = tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState.AssistantType.forNumber(assistantType_);
      return result == null ? tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState.AssistantType.UNRECOGNIZED : result;
    }

    public static final int FANSGROUPINTIMACYLEVEL_FIELD_NUMBER = 4;
    private int fansGroupIntimacyLevel_ = 0;
    /**
     * <code>uint32 fansGroupIntimacyLevel = 4;</code>
     * @return The fansGroupIntimacyLevel.
     */
    @java.lang.Override
    public int getFansGroupIntimacyLevel() {
      return fansGroupIntimacyLevel_;
    }

    public static final int NAMEPLATE_FIELD_NUMBER = 5;
    private tech.ordinaryroad.live.chat.client.kuaishou.protobuf.GzoneNameplateOuterClass.GzoneNameplate nameplate_;
    /**
     * <code>.GzoneNameplate nameplate = 5;</code>
     * @return Whether the nameplate field is set.
     */
    @java.lang.Override
    public boolean hasNameplate() {
      return nameplate_ != null;
    }
    /**
     * <code>.GzoneNameplate nameplate = 5;</code>
     * @return The nameplate.
     */
    @java.lang.Override
    public tech.ordinaryroad.live.chat.client.kuaishou.protobuf.GzoneNameplateOuterClass.GzoneNameplate getNameplate() {
      return nameplate_ == null ? tech.ordinaryroad.live.chat.client.kuaishou.protobuf.GzoneNameplateOuterClass.GzoneNameplate.getDefaultInstance() : nameplate_;
    }
    /**
     * <code>.GzoneNameplate nameplate = 5;</code>
     */
    @java.lang.Override
    public tech.ordinaryroad.live.chat.client.kuaishou.protobuf.GzoneNameplateOuterClass.GzoneNameplateOrBuilder getNameplateOrBuilder() {
      return nameplate_ == null ? tech.ordinaryroad.live.chat.client.kuaishou.protobuf.GzoneNameplateOuterClass.GzoneNameplate.getDefaultInstance() : nameplate_;
    }

    public static final int LIVEFANSGROUPSTATE_FIELD_NUMBER = 6;
    private tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveFansGroupStateOuterClass.LiveFansGroupState liveFansGroupState_;
    /**
     * <code>.LiveFansGroupState liveFansGroupState = 6;</code>
     * @return Whether the liveFansGroupState field is set.
     */
    @java.lang.Override
    public boolean hasLiveFansGroupState() {
      return liveFansGroupState_ != null;
    }
    /**
     * <code>.LiveFansGroupState liveFansGroupState = 6;</code>
     * @return The liveFansGroupState.
     */
    @java.lang.Override
    public tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveFansGroupStateOuterClass.LiveFansGroupState getLiveFansGroupState() {
      return liveFansGroupState_ == null ? tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveFansGroupStateOuterClass.LiveFansGroupState.getDefaultInstance() : liveFansGroupState_;
    }
    /**
     * <code>.LiveFansGroupState liveFansGroupState = 6;</code>
     */
    @java.lang.Override
    public tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveFansGroupStateOuterClass.LiveFansGroupStateOrBuilder getLiveFansGroupStateOrBuilder() {
      return liveFansGroupState_ == null ? tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveFansGroupStateOuterClass.LiveFansGroupState.getDefaultInstance() : liveFansGroupState_;
    }

    public static final int WEALTHGRADE_FIELD_NUMBER = 7;
    private int wealthGrade_ = 0;
    /**
     * <code>uint32 wealthGrade = 7;</code>
     * @return The wealthGrade.
     */
    @java.lang.Override
    public int getWealthGrade() {
      return wealthGrade_;
    }

    public static final int BADGEKEY_FIELD_NUMBER = 8;
    @SuppressWarnings("serial")
    private volatile java.lang.Object badgeKey_ = "";
    /**
     * <code>string badgeKey = 8;</code>
     * @return The badgeKey.
     */
    @java.lang.Override
    public java.lang.String getBadgeKey() {
      java.lang.Object ref = badgeKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        badgeKey_ = s;
        return s;
      }
    }
    /**
     * <code>string badgeKey = 8;</code>
     * @return The bytes for badgeKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBadgeKeyBytes() {
      java.lang.Object ref = badgeKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        badgeKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (isFromFansTop_ != false) {
        output.writeBool(1, isFromFansTop_);
      }
      if (isKoi_ != false) {
        output.writeBool(2, isKoi_);
      }
      if (assistantType_ != tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState.AssistantType.UNKNOWN_ASSISTANT_TYPE.getNumber()) {
        output.writeEnum(3, assistantType_);
      }
      if (fansGroupIntimacyLevel_ != 0) {
        output.writeUInt32(4, fansGroupIntimacyLevel_);
      }
      if (nameplate_ != null) {
        output.writeMessage(5, getNameplate());
      }
      if (liveFansGroupState_ != null) {
        output.writeMessage(6, getLiveFansGroupState());
      }
      if (wealthGrade_ != 0) {
        output.writeUInt32(7, wealthGrade_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(badgeKey_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, badgeKey_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (isFromFansTop_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isFromFansTop_);
      }
      if (isKoi_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isKoi_);
      }
      if (assistantType_ != tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState.AssistantType.UNKNOWN_ASSISTANT_TYPE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, assistantType_);
      }
      if (fansGroupIntimacyLevel_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, fansGroupIntimacyLevel_);
      }
      if (nameplate_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getNameplate());
      }
      if (liveFansGroupState_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getLiveFansGroupState());
      }
      if (wealthGrade_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, wealthGrade_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(badgeKey_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, badgeKey_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState)) {
        return super.equals(obj);
      }
      tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState other = (tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState) obj;

      if (getIsFromFansTop()
          != other.getIsFromFansTop()) return false;
      if (getIsKoi()
          != other.getIsKoi()) return false;
      if (assistantType_ != other.assistantType_) return false;
      if (getFansGroupIntimacyLevel()
          != other.getFansGroupIntimacyLevel()) return false;
      if (hasNameplate() != other.hasNameplate()) return false;
      if (hasNameplate()) {
        if (!getNameplate()
            .equals(other.getNameplate())) return false;
      }
      if (hasLiveFansGroupState() != other.hasLiveFansGroupState()) return false;
      if (hasLiveFansGroupState()) {
        if (!getLiveFansGroupState()
            .equals(other.getLiveFansGroupState())) return false;
      }
      if (getWealthGrade()
          != other.getWealthGrade()) return false;
      if (!getBadgeKey()
          .equals(other.getBadgeKey())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ISFROMFANSTOP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsFromFansTop());
      hash = (37 * hash) + ISKOI_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsKoi());
      hash = (37 * hash) + ASSISTANTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + assistantType_;
      hash = (37 * hash) + FANSGROUPINTIMACYLEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getFansGroupIntimacyLevel();
      if (hasNameplate()) {
        hash = (37 * hash) + NAMEPLATE_FIELD_NUMBER;
        hash = (53 * hash) + getNameplate().hashCode();
      }
      if (hasLiveFansGroupState()) {
        hash = (37 * hash) + LIVEFANSGROUPSTATE_FIELD_NUMBER;
        hash = (53 * hash) + getLiveFansGroupState().hashCode();
      }
      hash = (37 * hash) + WEALTHGRADE_FIELD_NUMBER;
      hash = (53 * hash) + getWealthGrade();
      hash = (37 * hash) + BADGEKEY_FIELD_NUMBER;
      hash = (53 * hash) + getBadgeKey().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LiveAudienceState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LiveAudienceState)
        tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.internal_static_LiveAudienceState_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.internal_static_LiveAudienceState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState.class, tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState.Builder.class);
      }

      // Construct using tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        isFromFansTop_ = false;
        isKoi_ = false;
        assistantType_ = 0;
        fansGroupIntimacyLevel_ = 0;
        nameplate_ = null;
        if (nameplateBuilder_ != null) {
          nameplateBuilder_.dispose();
          nameplateBuilder_ = null;
        }
        liveFansGroupState_ = null;
        if (liveFansGroupStateBuilder_ != null) {
          liveFansGroupStateBuilder_.dispose();
          liveFansGroupStateBuilder_ = null;
        }
        wealthGrade_ = 0;
        badgeKey_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.internal_static_LiveAudienceState_descriptor;
      }

      @java.lang.Override
      public tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState getDefaultInstanceForType() {
        return tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState.getDefaultInstance();
      }

      @java.lang.Override
      public tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState build() {
        tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState buildPartial() {
        tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState result = new tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.isFromFansTop_ = isFromFansTop_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.isKoi_ = isKoi_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.assistantType_ = assistantType_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.fansGroupIntimacyLevel_ = fansGroupIntimacyLevel_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.nameplate_ = nameplateBuilder_ == null
              ? nameplate_
              : nameplateBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.liveFansGroupState_ = liveFansGroupStateBuilder_ == null
              ? liveFansGroupState_
              : liveFansGroupStateBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.wealthGrade_ = wealthGrade_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.badgeKey_ = badgeKey_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState) {
          return mergeFrom((tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState other) {
        if (other == tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState.getDefaultInstance()) return this;
        if (other.getIsFromFansTop() != false) {
          setIsFromFansTop(other.getIsFromFansTop());
        }
        if (other.getIsKoi() != false) {
          setIsKoi(other.getIsKoi());
        }
        if (other.assistantType_ != 0) {
          setAssistantTypeValue(other.getAssistantTypeValue());
        }
        if (other.getFansGroupIntimacyLevel() != 0) {
          setFansGroupIntimacyLevel(other.getFansGroupIntimacyLevel());
        }
        if (other.hasNameplate()) {
          mergeNameplate(other.getNameplate());
        }
        if (other.hasLiveFansGroupState()) {
          mergeLiveFansGroupState(other.getLiveFansGroupState());
        }
        if (other.getWealthGrade() != 0) {
          setWealthGrade(other.getWealthGrade());
        }
        if (!other.getBadgeKey().isEmpty()) {
          badgeKey_ = other.badgeKey_;
          bitField0_ |= 0x00000080;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                isFromFansTop_ = input.readBool();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                isKoi_ = input.readBool();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                assistantType_ = input.readEnum();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                fansGroupIntimacyLevel_ = input.readUInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 42: {
                input.readMessage(
                    getNameplateFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                input.readMessage(
                    getLiveFansGroupStateFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 56: {
                wealthGrade_ = input.readUInt32();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              case 66: {
                badgeKey_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000080;
                break;
              } // case 66
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private boolean isFromFansTop_ ;
      /**
       * <code>bool isFromFansTop = 1;</code>
       * @return The isFromFansTop.
       */
      @java.lang.Override
      public boolean getIsFromFansTop() {
        return isFromFansTop_;
      }
      /**
       * <code>bool isFromFansTop = 1;</code>
       * @param value The isFromFansTop to set.
       * @return This builder for chaining.
       */
      public Builder setIsFromFansTop(boolean value) {

        isFromFansTop_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>bool isFromFansTop = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsFromFansTop() {
        bitField0_ = (bitField0_ & ~0x00000001);
        isFromFansTop_ = false;
        onChanged();
        return this;
      }

      private boolean isKoi_ ;
      /**
       * <code>bool isKoi = 2;</code>
       * @return The isKoi.
       */
      @java.lang.Override
      public boolean getIsKoi() {
        return isKoi_;
      }
      /**
       * <code>bool isKoi = 2;</code>
       * @param value The isKoi to set.
       * @return This builder for chaining.
       */
      public Builder setIsKoi(boolean value) {

        isKoi_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>bool isKoi = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsKoi() {
        bitField0_ = (bitField0_ & ~0x00000002);
        isKoi_ = false;
        onChanged();
        return this;
      }

      private int assistantType_ = 0;
      /**
       * <code>.LiveAudienceState.AssistantType assistantType = 3;</code>
       * @return The enum numeric value on the wire for assistantType.
       */
      @java.lang.Override public int getAssistantTypeValue() {
        return assistantType_;
      }
      /**
       * <code>.LiveAudienceState.AssistantType assistantType = 3;</code>
       * @param value The enum numeric value on the wire for assistantType to set.
       * @return This builder for chaining.
       */
      public Builder setAssistantTypeValue(int value) {
        assistantType_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.LiveAudienceState.AssistantType assistantType = 3;</code>
       * @return The assistantType.
       */
      @java.lang.Override
      public tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState.AssistantType getAssistantType() {
        tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState.AssistantType result = tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState.AssistantType.forNumber(assistantType_);
        return result == null ? tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState.AssistantType.UNRECOGNIZED : result;
      }
      /**
       * <code>.LiveAudienceState.AssistantType assistantType = 3;</code>
       * @param value The assistantType to set.
       * @return This builder for chaining.
       */
      public Builder setAssistantType(tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState.AssistantType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        assistantType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.LiveAudienceState.AssistantType assistantType = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAssistantType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        assistantType_ = 0;
        onChanged();
        return this;
      }

      private int fansGroupIntimacyLevel_ ;
      /**
       * <code>uint32 fansGroupIntimacyLevel = 4;</code>
       * @return The fansGroupIntimacyLevel.
       */
      @java.lang.Override
      public int getFansGroupIntimacyLevel() {
        return fansGroupIntimacyLevel_;
      }
      /**
       * <code>uint32 fansGroupIntimacyLevel = 4;</code>
       * @param value The fansGroupIntimacyLevel to set.
       * @return This builder for chaining.
       */
      public Builder setFansGroupIntimacyLevel(int value) {

        fansGroupIntimacyLevel_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 fansGroupIntimacyLevel = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearFansGroupIntimacyLevel() {
        bitField0_ = (bitField0_ & ~0x00000008);
        fansGroupIntimacyLevel_ = 0;
        onChanged();
        return this;
      }

      private tech.ordinaryroad.live.chat.client.kuaishou.protobuf.GzoneNameplateOuterClass.GzoneNameplate nameplate_;
      private com.google.protobuf.SingleFieldBuilderV3<
          tech.ordinaryroad.live.chat.client.kuaishou.protobuf.GzoneNameplateOuterClass.GzoneNameplate, tech.ordinaryroad.live.chat.client.kuaishou.protobuf.GzoneNameplateOuterClass.GzoneNameplate.Builder, tech.ordinaryroad.live.chat.client.kuaishou.protobuf.GzoneNameplateOuterClass.GzoneNameplateOrBuilder> nameplateBuilder_;
      /**
       * <code>.GzoneNameplate nameplate = 5;</code>
       * @return Whether the nameplate field is set.
       */
      public boolean hasNameplate() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>.GzoneNameplate nameplate = 5;</code>
       * @return The nameplate.
       */
      public tech.ordinaryroad.live.chat.client.kuaishou.protobuf.GzoneNameplateOuterClass.GzoneNameplate getNameplate() {
        if (nameplateBuilder_ == null) {
          return nameplate_ == null ? tech.ordinaryroad.live.chat.client.kuaishou.protobuf.GzoneNameplateOuterClass.GzoneNameplate.getDefaultInstance() : nameplate_;
        } else {
          return nameplateBuilder_.getMessage();
        }
      }
      /**
       * <code>.GzoneNameplate nameplate = 5;</code>
       */
      public Builder setNameplate(tech.ordinaryroad.live.chat.client.kuaishou.protobuf.GzoneNameplateOuterClass.GzoneNameplate value) {
        if (nameplateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          nameplate_ = value;
        } else {
          nameplateBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.GzoneNameplate nameplate = 5;</code>
       */
      public Builder setNameplate(
          tech.ordinaryroad.live.chat.client.kuaishou.protobuf.GzoneNameplateOuterClass.GzoneNameplate.Builder builderForValue) {
        if (nameplateBuilder_ == null) {
          nameplate_ = builderForValue.build();
        } else {
          nameplateBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.GzoneNameplate nameplate = 5;</code>
       */
      public Builder mergeNameplate(tech.ordinaryroad.live.chat.client.kuaishou.protobuf.GzoneNameplateOuterClass.GzoneNameplate value) {
        if (nameplateBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0) &&
            nameplate_ != null &&
            nameplate_ != tech.ordinaryroad.live.chat.client.kuaishou.protobuf.GzoneNameplateOuterClass.GzoneNameplate.getDefaultInstance()) {
            getNameplateBuilder().mergeFrom(value);
          } else {
            nameplate_ = value;
          }
        } else {
          nameplateBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.GzoneNameplate nameplate = 5;</code>
       */
      public Builder clearNameplate() {
        bitField0_ = (bitField0_ & ~0x00000010);
        nameplate_ = null;
        if (nameplateBuilder_ != null) {
          nameplateBuilder_.dispose();
          nameplateBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.GzoneNameplate nameplate = 5;</code>
       */
      public tech.ordinaryroad.live.chat.client.kuaishou.protobuf.GzoneNameplateOuterClass.GzoneNameplate.Builder getNameplateBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getNameplateFieldBuilder().getBuilder();
      }
      /**
       * <code>.GzoneNameplate nameplate = 5;</code>
       */
      public tech.ordinaryroad.live.chat.client.kuaishou.protobuf.GzoneNameplateOuterClass.GzoneNameplateOrBuilder getNameplateOrBuilder() {
        if (nameplateBuilder_ != null) {
          return nameplateBuilder_.getMessageOrBuilder();
        } else {
          return nameplate_ == null ?
              tech.ordinaryroad.live.chat.client.kuaishou.protobuf.GzoneNameplateOuterClass.GzoneNameplate.getDefaultInstance() : nameplate_;
        }
      }
      /**
       * <code>.GzoneNameplate nameplate = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          tech.ordinaryroad.live.chat.client.kuaishou.protobuf.GzoneNameplateOuterClass.GzoneNameplate, tech.ordinaryroad.live.chat.client.kuaishou.protobuf.GzoneNameplateOuterClass.GzoneNameplate.Builder, tech.ordinaryroad.live.chat.client.kuaishou.protobuf.GzoneNameplateOuterClass.GzoneNameplateOrBuilder> 
          getNameplateFieldBuilder() {
        if (nameplateBuilder_ == null) {
          nameplateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              tech.ordinaryroad.live.chat.client.kuaishou.protobuf.GzoneNameplateOuterClass.GzoneNameplate, tech.ordinaryroad.live.chat.client.kuaishou.protobuf.GzoneNameplateOuterClass.GzoneNameplate.Builder, tech.ordinaryroad.live.chat.client.kuaishou.protobuf.GzoneNameplateOuterClass.GzoneNameplateOrBuilder>(
                  getNameplate(),
                  getParentForChildren(),
                  isClean());
          nameplate_ = null;
        }
        return nameplateBuilder_;
      }

      private tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveFansGroupStateOuterClass.LiveFansGroupState liveFansGroupState_;
      private com.google.protobuf.SingleFieldBuilderV3<
          tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveFansGroupStateOuterClass.LiveFansGroupState, tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveFansGroupStateOuterClass.LiveFansGroupState.Builder, tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveFansGroupStateOuterClass.LiveFansGroupStateOrBuilder> liveFansGroupStateBuilder_;
      /**
       * <code>.LiveFansGroupState liveFansGroupState = 6;</code>
       * @return Whether the liveFansGroupState field is set.
       */
      public boolean hasLiveFansGroupState() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>.LiveFansGroupState liveFansGroupState = 6;</code>
       * @return The liveFansGroupState.
       */
      public tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveFansGroupStateOuterClass.LiveFansGroupState getLiveFansGroupState() {
        if (liveFansGroupStateBuilder_ == null) {
          return liveFansGroupState_ == null ? tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveFansGroupStateOuterClass.LiveFansGroupState.getDefaultInstance() : liveFansGroupState_;
        } else {
          return liveFansGroupStateBuilder_.getMessage();
        }
      }
      /**
       * <code>.LiveFansGroupState liveFansGroupState = 6;</code>
       */
      public Builder setLiveFansGroupState(tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveFansGroupStateOuterClass.LiveFansGroupState value) {
        if (liveFansGroupStateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          liveFansGroupState_ = value;
        } else {
          liveFansGroupStateBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>.LiveFansGroupState liveFansGroupState = 6;</code>
       */
      public Builder setLiveFansGroupState(
          tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveFansGroupStateOuterClass.LiveFansGroupState.Builder builderForValue) {
        if (liveFansGroupStateBuilder_ == null) {
          liveFansGroupState_ = builderForValue.build();
        } else {
          liveFansGroupStateBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>.LiveFansGroupState liveFansGroupState = 6;</code>
       */
      public Builder mergeLiveFansGroupState(tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveFansGroupStateOuterClass.LiveFansGroupState value) {
        if (liveFansGroupStateBuilder_ == null) {
          if (((bitField0_ & 0x00000020) != 0) &&
            liveFansGroupState_ != null &&
            liveFansGroupState_ != tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveFansGroupStateOuterClass.LiveFansGroupState.getDefaultInstance()) {
            getLiveFansGroupStateBuilder().mergeFrom(value);
          } else {
            liveFansGroupState_ = value;
          }
        } else {
          liveFansGroupStateBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>.LiveFansGroupState liveFansGroupState = 6;</code>
       */
      public Builder clearLiveFansGroupState() {
        bitField0_ = (bitField0_ & ~0x00000020);
        liveFansGroupState_ = null;
        if (liveFansGroupStateBuilder_ != null) {
          liveFansGroupStateBuilder_.dispose();
          liveFansGroupStateBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.LiveFansGroupState liveFansGroupState = 6;</code>
       */
      public tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveFansGroupStateOuterClass.LiveFansGroupState.Builder getLiveFansGroupStateBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getLiveFansGroupStateFieldBuilder().getBuilder();
      }
      /**
       * <code>.LiveFansGroupState liveFansGroupState = 6;</code>
       */
      public tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveFansGroupStateOuterClass.LiveFansGroupStateOrBuilder getLiveFansGroupStateOrBuilder() {
        if (liveFansGroupStateBuilder_ != null) {
          return liveFansGroupStateBuilder_.getMessageOrBuilder();
        } else {
          return liveFansGroupState_ == null ?
              tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveFansGroupStateOuterClass.LiveFansGroupState.getDefaultInstance() : liveFansGroupState_;
        }
      }
      /**
       * <code>.LiveFansGroupState liveFansGroupState = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveFansGroupStateOuterClass.LiveFansGroupState, tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveFansGroupStateOuterClass.LiveFansGroupState.Builder, tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveFansGroupStateOuterClass.LiveFansGroupStateOrBuilder> 
          getLiveFansGroupStateFieldBuilder() {
        if (liveFansGroupStateBuilder_ == null) {
          liveFansGroupStateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveFansGroupStateOuterClass.LiveFansGroupState, tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveFansGroupStateOuterClass.LiveFansGroupState.Builder, tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveFansGroupStateOuterClass.LiveFansGroupStateOrBuilder>(
                  getLiveFansGroupState(),
                  getParentForChildren(),
                  isClean());
          liveFansGroupState_ = null;
        }
        return liveFansGroupStateBuilder_;
      }

      private int wealthGrade_ ;
      /**
       * <code>uint32 wealthGrade = 7;</code>
       * @return The wealthGrade.
       */
      @java.lang.Override
      public int getWealthGrade() {
        return wealthGrade_;
      }
      /**
       * <code>uint32 wealthGrade = 7;</code>
       * @param value The wealthGrade to set.
       * @return This builder for chaining.
       */
      public Builder setWealthGrade(int value) {

        wealthGrade_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 wealthGrade = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearWealthGrade() {
        bitField0_ = (bitField0_ & ~0x00000040);
        wealthGrade_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object badgeKey_ = "";
      /**
       * <code>string badgeKey = 8;</code>
       * @return The badgeKey.
       */
      public java.lang.String getBadgeKey() {
        java.lang.Object ref = badgeKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          badgeKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string badgeKey = 8;</code>
       * @return The bytes for badgeKey.
       */
      public com.google.protobuf.ByteString
          getBadgeKeyBytes() {
        java.lang.Object ref = badgeKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          badgeKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string badgeKey = 8;</code>
       * @param value The badgeKey to set.
       * @return This builder for chaining.
       */
      public Builder setBadgeKey(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        badgeKey_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>string badgeKey = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearBadgeKey() {
        badgeKey_ = getDefaultInstance().getBadgeKey();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      /**
       * <code>string badgeKey = 8;</code>
       * @param value The bytes for badgeKey to set.
       * @return This builder for chaining.
       */
      public Builder setBadgeKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        badgeKey_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LiveAudienceState)
    }

    // @@protoc_insertion_point(class_scope:LiveAudienceState)
    private static final tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState();
    }

    public static tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LiveAudienceState>
        PARSER = new com.google.protobuf.AbstractParser<LiveAudienceState>() {
      @java.lang.Override
      public LiveAudienceState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<LiveAudienceState> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LiveAudienceState> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveAudienceStateOuterClass.LiveAudienceState getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LiveAudienceState_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LiveAudienceState_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027LiveAudienceState.proto\032\024GzoneNameplat" +
      "e.proto\032\030LiveFansGroupState.proto\"\322\002\n\021Li" +
      "veAudienceState\022\025\n\risFromFansTop\030\001 \001(\010\022\r" +
      "\n\005isKoi\030\002 \001(\010\0227\n\rassistantType\030\003 \001(\0162 .L" +
      "iveAudienceState.AssistantType\022\036\n\026fansGr" +
      "oupIntimacyLevel\030\004 \001(\r\022\"\n\tnameplate\030\005 \001(" +
      "\0132\017.GzoneNameplate\022/\n\022liveFansGroupState" +
      "\030\006 \001(\0132\023.LiveFansGroupState\022\023\n\013wealthGra" +
      "de\030\007 \001(\r\022\020\n\010badgeKey\030\010 \001(\t\"B\n\rAssistantT" +
      "ype\022\032\n\026UNKNOWN_ASSISTANT_TYPE\020\000\022\t\n\005SUPER" +
      "\020\001\022\n\n\006JUNIOR\020\002B6\n4tech.ordinaryroad.live" +
      ".chat.client.kuaishou.protobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          tech.ordinaryroad.live.chat.client.kuaishou.protobuf.GzoneNameplateOuterClass.getDescriptor(),
          tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveFansGroupStateOuterClass.getDescriptor(),
        });
    internal_static_LiveAudienceState_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LiveAudienceState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LiveAudienceState_descriptor,
        new java.lang.String[] { "IsFromFansTop", "IsKoi", "AssistantType", "FansGroupIntimacyLevel", "Nameplate", "LiveFansGroupState", "WealthGrade", "BadgeKey", });
    tech.ordinaryroad.live.chat.client.kuaishou.protobuf.GzoneNameplateOuterClass.getDescriptor();
    tech.ordinaryroad.live.chat.client.kuaishou.protobuf.LiveFansGroupStateOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
