package org.ruoyi.common.wechat.web.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWxRobRelation<M extends BaseWxRobRelation<M>> extends Model<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}

	public Long getId() {
		return getLong("id");
	}

	public M setOutKey(String outKey) {
		set("out_key", outKey);
		return (M)this;
	}

	public String getOutKey() {
		return getStr("out_key");
	}

	public M setUniqueKey(String uniqueKey) {
		set("unique_key", uniqueKey);
		return (M)this;
	}

	public String getUniqueKey() {
		return getStr("unique_key");
	}

	public M setNickName(String nickName) {
		set("nick_name", nickName);
		return (M)this;
	}

	public String getNickName() {
		return getStr("nick_name");
	}

	public M setToGroup(Boolean toGroup) {
		set("to_group", toGroup);
		return (M)this;
	}

	public Boolean getToGroup() {
		return get("to_group");
	}

	public M setEnable(Boolean enable) {
		set("enable", enable);
		return (M)this;
	}

	public Boolean getEnable() {
		return get("enable");
	}

	public M setWhiteList(String whiteList) {
		set("white_list", whiteList);
		return (M)this;
	}

	public String getWhiteList() {
		return getStr("white_list");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
